# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/conjugo/all/conjugo.rbi
#
# conjugo-0.1.0

module Conjugo
end
class Conjugo::Conjugator
  def all_subjects(*args, &blk); end
  def all_verbs(*args, &blk); end
  def valid_subject?(*args, &blk); end
  def valid_verb?(*args, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
